# Based on https://github.com/PrakashTrove/AWS-CodeBuild-NetCore/blob/master/buildspec.yml
# AWS CodeBuild spec to build an Elastic Beanstalk artifact for AWS CodePipeline to deploy
version: 0.2
    
phases:   
  install:
    runtime-versions:
      dotnet: 6.0
      
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore AWSCodePipelineDemo.csproj
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet build AWSCodePipelineDemo.csproj
      
  post_build:
    commands:
      - echo ASPNETCORE_ENVIRONMENT is $ASPNETCORE_ENVIRONMENT
      - echo Publish started on `date`
      - dotnet publish -c Release -r linux-x64 --self-contained false AWSCodePipelineDemo.csproj
      
artifacts:
  files:
    - '**/*'
  base-directory: ./bin/Release/netcoreapp6.0/linux-x64/publish/
  discard-paths: no